services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin

    ports:
      - "8096:8096"
      - "7359:7359/udp"

    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - /srv/media:/media

    restart: unless-stopped
